# Generated by Django 4.2.4 on 2023-08-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
