# Generated by Django 4.2.4 on 2023-08-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_review_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rank',
            new_name='star_rating',
        ),
    ]
