# Generated by Django 4.2.4 on 2023-08-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_menucategory_name_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(default=7, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
