# Generated by Django 4.2.4 on 2023-08-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_menuitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='home.menuitem'),
            preserve_default=False,
        ),
    ]
