# Generated by Django 4.2.4 on 2023-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='slug',
            field=models.CharField(default=0, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
