# Generated by Django 4.2.4 on 2023-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='labels',
            field=models.CharField(choices=[('special', 'special')], default=4, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
