# Generated by Django 4.2.4 on 2023-09-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_menuitem_labels_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='labels',
            field=models.CharField(blank=True, choices=[('special', 'special')], max_length=50),
        ),
    ]
