# Generated by Django 4.2.4 on 2023-09-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_menuitem_image_menuitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemimage',
            name='slug',
            field=models.CharField(default=4, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
