# Generated by Django 4.2.4 on 2023-09-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_cart_items_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items_img',
        ),
    ]
